version: '2'
services:
  solr:
    image: solr
    container_name: solr    
    ports:
     - "9983:9983"
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
      - ./conf/stopwords-es.txt:/opt/solr/server/solr/configsets/_default/conf/stopwords.txt
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
volumes:
  data: